# Generated by Django 6.0.5 on 2026-05-17 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Oportunidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("consultoria", "Consultoría B2B"),
                            ("diseno", "Diseño y Branding"),
                            ("tecnologia", "Tecnología"),
                            ("marketing", "Marketing Digital"),
                            ("suministros", "Suministros"),
                            ("educacion", "Educación"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "urgencia",
                    models.CharField(
                        choices=[
                            ("alta", "Alta"),
                            ("media", "Media"),
                            ("baja", "Baja"),
                        ],
                        default="media",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("activa", "Activa"),
                            ("cerrada", "Cerrada"),
                            ("vencida", "Vencida"),
                        ],
                        default="activa",
                        max_length=10,
                    ),
                ),
                (
                    "presupuesto_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "presupuesto_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("etiquetas", models.CharField(blank=True, max_length=200)),
                ("vence_el", models.DateField()),
                ("creada_el", models.DateTimeField(auto_now_add=True)),
                (
                    "publicada_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oportunidades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Postulacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mensaje", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aceptada", "Aceptada"),
                            ("rechazada", "Rechazada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("postulada_el", models.DateTimeField(auto_now_add=True)),
                (
                    "oportunidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postulaciones",
                        to="opportunities.oportunidad",
                    ),
                ),
                (
                    "postulante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postulaciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"unique_together": {("oportunidad", "postulante")},},
        ),
    ]
