# Generated by Django 6.0.5 on 2026-08-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="oportunidad",
            name="categoria_otro",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AlterField(
            model_name="oportunidad",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("consultoria", "Consultoría y Negocios"),
                    ("marketing_branding", "Marketing y Diseño"),
                    ("tecnologia", "Tecnología"),
                    ("educacion", "Educación y Formación"),
                    ("salud_bienestar", "Salud y Bienestar"),
                    ("otro", "Otro"),
                ],
                max_length=20,
            ),
        ),
    ]
