# Generated by Django 6.0.5 on 2026-05-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="limite_asistentes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("confirmada", "Confirmada"),
                    ("cancelada", "Cancelada"),
                    ("pendiente", "Pendiente"),
                    ("ausente", "Ausente"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
    ]
