# Generated by Django 6.0.5 on 2026-05-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_limite_asistentes_alter_attendance_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="costo",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
