# Generated by Django 6.0.5 on 2026-05-25 15:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("imagen", models.ImageField(upload_to="banners/")),
                ("url_destino", models.URLField()),
                ("activo", models.BooleanField(default=True)),
                ("fecha_inicio", models.DateField(default=django.utils.timezone.now)),
                ("fecha_fin", models.DateField()),
                (
                    "posicion",
                    models.CharField(
                        choices=[
                            ("pre_footer", "Antes del Footer"),
                            ("entre_secciones", "Entre Secciones"),
                        ],
                        default="pre_footer",
                        max_length=50,
                    ),
                ),
            ],
            options={"verbose_name": "Banner", "verbose_name_plural": "Banners",},
        ),
    ]
