# Generated by Django 6.0.5 on 2026-05-28 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banners", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="banner",
            options={
                "ordering": ["-creado_en"],
                "verbose_name": "Banner",
                "verbose_name_plural": "Banners",
            },
        ),
        migrations.AddField(
            model_name="banner",
            name="creado_en",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="banner",
            name="posicion",
            field=models.CharField(
                choices=[
                    ("landing_pre_footer", "Landing — Antes del Footer"),
                    ("landing_entre_secciones", "Landing — Entre Secciones"),
                    ("directorio", "Directorio de Miembros"),
                    ("dashboard", "Dashboard / Home del Usuario"),
                    ("global", "Todas las Páginas (Banner Global)"),
                ],
                default="landing_pre_footer",
                max_length=50,
            ),
        ),
    ]
