# Generated by Django 6.0.5 on 2026-05-17 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Institucion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("gobierno", "Gobierno"),
                            ("refugio", "Refugio"),
                            ("fiscalia", "Fiscalía"),
                            ("dif", "DIF"),
                        ],
                        max_length=20,
                    ),
                ),
                ("telefono", models.CharField(max_length=20)),
                ("horario", models.CharField(max_length=100)),
                ("direccion", models.CharField(max_length=200)),
                ("emergencias_24h", models.BooleanField(default=False)),
                ("activa", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="SolicitudApoyo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("violencia", "Violencia Doméstica"),
                            ("psicologico", "Apoyo Psicológico"),
                            ("legal", "Asesoría Legal"),
                            ("solidaridad", "Solidaridad de Red"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("atendida", "Atendida"),
                            ("cerrada", "Cerrada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("creada_el", models.DateTimeField(auto_now_add=True)),
                (
                    "usuaria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitudes_apoyo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name_plural": "Solicitudes de Apoyo",},
        ),
    ]
