# Generated by Django 6.0.5 on 2026-05-17 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("consultoria", "Consultoría"),
                            ("workshop", "Workshop"),
                            ("estrategia", "Estrategia"),
                            ("branding", "Branding"),
                            ("tecnologia", "Tecnología"),
                            ("marketing", "Marketing"),
                            ("educacion", "Educación"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "precio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("precio_personalizado", models.BooleanField(default=False)),
                ("activo", models.BooleanField(default=True)),
                ("creado_el", models.DateTimeField(auto_now_add=True)),
                (
                    "proveedora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servicios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
