# Generated by Django 6.0.5 on 2026-05-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicio",
            name="categoria",
            field=models.CharField(max_length=80),
        ),
    ]
