# Generated by Django 6.0.5 on 2026-08-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_alter_servicio_categoria"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicio", options={"ordering": ["-creado_el"]},
        ),
        migrations.AddField(
            model_name="servicio",
            name="categoria_otro",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AlterField(
            model_name="servicio",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("consultoria", "Consultoría y Negocios"),
                    ("marketing_branding", "Marketing y Diseño"),
                    ("tecnologia", "Tecnología"),
                    ("educacion", "Educación y Formación"),
                    ("salud_bienestar", "Salud y Bienestar"),
                    ("otro", "Otro"),
                ],
                default="consultoria",
                max_length=20,
            ),
        ),
    ]
