# Generated by Django 6.0.5 on 2026-05-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("cover_image", models.ImageField(upload_to="articles/covers/")),
                (
                    "external_url",
                    models.URLField(help_text="Link directo al artículo en la revista"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("recetas", "Recetas"),
                            ("bienestar", "Bienestar"),
                            ("negocios", "Consejos de Negocios"),
                            ("vida_familia", "Vida y Familia"),
                            ("tendencias", "Tendencias"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Aparece como artículo destacado grande",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Orden de aparición, menor = primero"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Artículo",
                "verbose_name_plural": "Artículos",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
