# Generated by Django 6.0.5 on 2026-06-29 20:31

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="cursos/",
                        validators=[courses.models.validar_imagen],
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("sensibilizacion", "Formación en Sensibilización"),
                            ("academico", "Programa Académico"),
                            ("liderazgo", "Liderazgo y Negocios"),
                            ("tecnologia", "Tecnología"),
                            ("finanzas", "Finanzas"),
                            ("marketing", "Marketing Digital"),
                            ("otro", "Otro"),
                        ],
                        default="otro",
                        max_length=50,
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("basico", "Básico"),
                            ("intermedio", "Intermedio"),
                            ("avanzado", "Avanzado"),
                        ],
                        default="basico",
                        max_length=20,
                    ),
                ),
                (
                    "duracion_horas",
                    models.PositiveIntegerField(help_text="Duración en horas"),
                ),
                ("link_externo", models.URLField(blank=True, null=True)),
                ("instructor", models.CharField(blank=True, max_length=150, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Curso",
                "verbose_name_plural": "Cursos",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.AlterUniqueTogether(name="enrollment", unique_together=None,),
        migrations.RemoveField(model_name="enrollment", name="course",),
        migrations.RemoveField(model_name="enrollment", name="user",),
        migrations.DeleteModel(name="Course",),
        migrations.DeleteModel(name="Enrollment",),
    ]