# Generated by Django 6.0.5 on 2026-05-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="instagram",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="is_founder",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user", name="linkedin", field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="twitter",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="business_sector",
            field=models.CharField(
                blank=True,
                choices=[
                    ("textil", "Textil y Confección"),
                    ("arte", "Arte y Diseño"),
                    ("logistica", "Logística y Transporte"),
                    ("tecnologia", "Tecnología e IT"),
                    ("financiero", "Servicios Financieros"),
                    ("educacion", "Educación"),
                    ("salud", "Salud y Bienestar"),
                    ("agricultura", "Agricultura Sostenible"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="municipality",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tlaxcala_centro", "Tlaxcala Centro"),
                    ("apizaco", "Apizaco"),
                    ("huamantla", "Huamantla"),
                    ("chiautempan", "Chiautempan"),
                    ("tlaxco", "Tlaxco"),
                    ("zacatelco", "Zacatelco"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="years_leading",
            field=models.CharField(
                blank=True,
                choices=[
                    ("menos_1", "Menos de 1"),
                    ("1_3", "1 a 3"),
                    ("3_5", "3 a 5"),
                    ("mas_5", "Más de 5"),
                ],
                max_length=10,
            ),
        ),
    ]
