# Generated by Django 6.0.5 on 2026-05-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_instagram_user_is_founder_user_linkedin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("aprobada", "Aprobada"),
                    ("rechazada", "Rechazada"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
    ]
