# Generated by Django 6.0.5 on 2026-05-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="rechazo_motivo",
            field=models.TextField(blank=True),
        ),
    ]
