# Generated by Django 6.0.5 on 2026-05-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_rechazo_motivo"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="municipality",),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="user",
            name="business_sector",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
