# Generated by Django 6.0.5 on 2026-05-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_user_municipality_user_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="banner_imagen",
            field=models.ImageField(blank=True, null=True, upload_to="banners/"),
        ),
        migrations.AddField(
            model_name="user",
            name="en_rotacion",
            field=models.BooleanField(default=False),
        ),
    ]
