# Generated by Django 6.0.5 on 2026-05-28 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_banner_imagen_user_en_rotacion"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="banner_imagen",),
        migrations.RemoveField(model_name="user", name="en_rotacion",),
    ]
