# Generated by Django 6.0.5 on 2026-08-07 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_user_banner_imagen_remove_user_en_rotacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Solo dígitos, con o sin lada 52. Este dato es visible en el perfil público.",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El teléfono debe tener 10 dígitos (o incluir la lada 52 de México).",
                        regex="^\\d{10}$|^52\\d{10}$",
                    )
                ],
            ),
        ),
    ]
